# Берём node.js v8 в качестве родительского образа
FROM node:12 as dev-stage
# Устанавливаем рабочую директорию
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
# Копируем файлы yarn.lock и package.json в рабочую директорию
COPY package.json yarn.lock /app/
# Устанавливаем зависимости
RUN yarn install --silent
COPY . /app/
# Открываем порт 3000
EXPOSE 3000
# Запускаем React-приложение после запуска контейнера
CMD ["yarn", "start"]
